production:
  primary:
    database: <your_primary_database>
    username: <your_db_username>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] %>

  queue:
    database: <your_queue_database>
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] %>

  cache:
    database: <your_cache_database>
    username: <%= ENV['CACHE_USERNAME'] %>
    password: <%= ENV['CACHE_PASSWORD'] %>
    host: <%= ENV['CACHE_HOST'] %>
    port: <%= ENV['CACHE_PORT'] %>
