production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: 5
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    adapter: postgresql
    encoding: unicode
    pool: 5
    url: <%= ENV["DATABASE_URL"] %>
