default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'your_development_db_name' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'your_test_db_name' %>

production:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'your_production_db_name' %>
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] || 5432 %>
